export const TEST_NOW = 'TEST_NOW';
export const FETCH_LEADS = 'FETCH_LEADS';
export const FETCH_LEADS_SUCCESS = 'FETCH_LEADS_SUCCESS';
export const SUBMIT_LEAD_FORM = 'SUBMIT_LEAD_FORM';
export const SUBMIT_LEAD_FORM_SUCCEEDED = 'SUBMIT_LEAD_FORM_SUCCEEDED';
export const SUBMIT_LEAD_FORM_FAILED = 'SUBMIT_LEAD_FORM_FAILED';
